#!/bin/bash

###############################################################################
#  Copyright (C) 2002-2004 Antonio Manuel Dias
#
#  E permitida a copia, distribuicao e/ou modificacao deste script sob os
#  termos da Licenca Publica Geral GNU (GNU General Public License), Versao 2,
#  publicada pela Free Software Foundation.
#  Podes consultar uma copia desta licenca no endereco Web (Internet)
#     http://maracuja.homeip.net/gpl.html
#
#  contacto: amdias@netvisao.pt
###############################################################################

###############################################################################
# Historia:
#   versao 1.0 (2004/Jun.27, Antonio Manuel Dias)
#          Reescrito de forma a poder ser reinicializado sem carregar de novo
#          os módulos do netfilter
#   versao 0.7 (2003/Jun.23, Antonio Manuel Dias)
#          Carregar módulos ip_conntrack_irc e ip_nat_irc para possibilitar
#          ligações DCC no IRC
#   versao 0.6 (2003/Jun.10, sugerido por Auston Rodrigo Damazio)
#          Abrir entrada para todo o trafego proveniente interface de rede
#          da rede interna para possibilitar redes por DHCP
#   versao 0.5 (2003/Abr.15, sugerido por Alexandre Salvador)
#          Limpeza das tabelas de NAT
#   versao 0.4 (2002/Dez.22, sugerido por falco)
#          Correccao de bugs que impediam o acesso ao exterior a partir
#          da maquina local, iclusive na partilha de internet
#   versao 0.3 (2002/Dez.22, sugerido por higuita)
#          Possibilitar o acesso ao servidor FTP em modo "active"
#   versao 0.2 (2002/Dez.21, sugerido por higuita)
#          Possibilitar o acesso do servidor DHCP ao cliente local
#


###############################################################################
# Interface de rede externa (para a internet)
# Altera consoante o teu caso. Normalmente (MAS SEM GARANTIAS) sao:
#   eth0 ou eth1 - ligacao por cabo (atraves de placa de rede ethernet)
#   ppp0 - ligacao por modem ou ADSL

#IRE=eth0
#IRE=eth1
IRE=ppp0


###############################################################################
# Interface de rede interna
# Altera consoante o teu caso. Normalmente (MAS SEM GARANTIAS) sao:
#   eth0 ou eth1

#IRI=eth0
#IRI=eth1


###############################################################################
# Carregar / remover netfilter

load_netfilter () {
  modprobe ip_conntrack
  modprobe ip_conntrack_ftp
  modprobe ip_conntrack_irc
}

###############################################################################
# Limpar tabelas

clear_tables () {
  iptables -F INPUT
  iptables -F OUTPUT
  iptables -F FORWARD
  iptables -t nat -F
  echo 0 > /proc/sys/net/ipv4/ip_forward
}

###############################################################################
# Partilha de ligação a internet

inet_conn_share () {
  modprobe ip_nat_irc
  iptables -t nat -A POSTROUTING -o $IRE -j MASQUERADE
  iptables -A FORWARD -i $IRE -m state --state NEW,INVALID -j DROP
  echo 1 > /proc/sys/net/ipv4/ip_forward
  iptables -A OUTPUT -m state -p icmp --state INVALID -j DROP
  iptables -A INPUT -i $IRI -j ACCEPT
}

###############################################################################
# Carregar tabelas

load_tables () {
  # ignorar tudo que não for *explicitamente* permitido
  iptables -P INPUT DROP
  iptables -A INPUT -i $IRE -m state --state INVALID -j DROP

  # permitir a entrada as nossas ligacoes
  iptables -A INPUT -i lo -j ACCEPT
  iptables -A INPUT -i $IRE -m state --state RELATED -j ACCEPT
  iptables -A INPUT -i $IRE -m state --state ESTABLISHED -j ACCEPT

  # partilhar ligacao a internet
  #inet_conn_share
  
  # permitir o uso de BitTorrent
  iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport 34000:34200 -j ACCEPT

  # permitir o acesso externo ao servidor de FTP (transferencia de ficheiros)
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport ftp -j ACCEPT
  # permitir o acesso ao servidor de FTP quando em modo "active"
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport ftp-data -j ACCEPT

  # permitir o acesso externo ao servidor de SSH (login remoto)
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport ssh -j ACCEPT

  # permitir o acesso externo aos servidores de HTTP e HTTPS (servidores web)
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport http -j ACCEPT
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport https -j ACCEPT

  # permitir o acesso externo aos servidores de correio electronico
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport smtp -j ACCEPT
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport smtps -j ACCEPT
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport pop3 -j ACCEPT
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport pop3s -j ACCEPT
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport imap -j ACCEPT
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport imaps -j ACCEPT

  # permitir o acesso externo ao servidor de news
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport nntp -j ACCEPT

  # permitir o acesso externo aos servidores de IRC
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport irc -j ACCEPT
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport ircs -j ACCEPT

  # permitir o acesso externo aos servidores de Jabber
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport jabber -j ACCEPT
  #iptables -A INPUT -i $IRE -m state --state NEW -p tcp --dport jabbers -j ACCEPT
  
  # permitir efectuar ping a partir do exterior
  #iptables -A INPUT -i $IRE -m state --state NEW -p icmp -j ACCEPT
}

###############################################################################
# Inicializacao do script
#  parametros possiveis:
#    - start: carrega as regras da firewall e os modulos necessarios
#    - restart: limpa as tabelas e volta a carrega-las (para usar depois de
#               alterar as regras com a firewall a correr)
#    - stop: limpa todas as regras e abre a cadeia de entrada (a maquina fica
#            desprotegida: so deve ser feito quando desligado da internet)

case "$1" in
  start)
    load_netfilter
    clear_tables
    load_tables
    ;;

  restart)
    clear_tables
    load_tables
    ;;

  stop)
    clear_tables
    iptables -P INPUT ACCEPT
    ;;

esac
